version: '3.8'
services:
  webapi:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5142

  db:
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
      
volumes: 
  dbdata: