version: '3.8'
services:
  webapi:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JWT=
      - TTSKEY=
      - REGION=
      - MYSQLCONN=Server=db; port=3306; Database=db; Uid=user; Pwd=password;

  db:
    image: mysql:8.0.19
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-user", "-password"]
      interval: 10s
      timeout: 5s
      retries: 3
  angular:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
volumes: 
  dbdata: